name: 'helllicht/ftp-sync'
description: 'helllicht internal sync-action'

inputs:
    host:
        description: 'Host (e.g. "my-sftp-url.com")'
        required: true
    #port:
    #    description: 'Port [default: "22"]'
    #    required: false
    #    default: '22'
    username:
        description: 'Username'
        required: true
    password:
        description: 'Password'
        required: true
    localDir:
        description: 'Directory that should be uploaded'
        required: true
    uploadPath:
        description: 'Path where the sync directory is'
        required: true

runs:
    using: "composite"
    steps:
        -   run: echo "Start helllicht/ftp-sync"
            shell: bash
        -   run: |
                chmod +x ${{ github.action_path }}/sync.sh
                bash ${{ github.action_path }}/sync.sh \
                    -h=${{ inputs.host }} \
                    -u=${{ inputs.username }} \
                    -p=${{ inputs.password }} \
                    -l=${{ inputs.localDir }} \
                    -r=${{ inputs.uploadPath }}
            shell: bash
