name: 'helllicht/ftp-sync'
description: 'helllicht internal sync-action'

inputs:
    host:
        description: 'Host (e.g. "my-sftp-url.com")'
        required: true
    #port:
    #    description: 'Port [default: "22"]'
    #    required: false
    #    default: '22'
    #forceVendor:
    #    description: 'Always upload vendor (default: "false") ["false", all other strings are true!]'
    #    required: false
    #    default: 'false'
    username:
        description: 'Username'
        required: true
    password:
        description: 'Password'
        required: true
    localDir:
        description: 'Directory that should be uploaded'
        required: true
    uploadPath:
        description: 'Path where the sync directory is'
        required: true
    forceSSL:
        description: 'Just use SSL connection (default: "true") ["true", all other strings are false!]'
        required: false
        default: 'true'
    lftp:
        description: 'Select lftp version (default: "4.9.2")'
        required: false
        default: '4.9.2'

runs:
    using: "composite"
    steps:
        -   run: echo "Start helllicht/ftp-sync"
            shell: bash
        -   run: |
                chmod +x ${{ github.action_path }}/sync.sh
                bash ${{ github.action_path }}/sync.sh \
                    -s=${{ github.action_path }} \
                    -h=${{ inputs.host }} \
                    -u=${{ inputs.username }} \
                    -p=${{ inputs.password }} \
                    -l=${{ inputs.localDir }} \
                    -r=${{ inputs.uploadPath }} \
                    -S=${{ inputs.forceSSL }} \
                    -lftp=${{ inputs.lftp }} \
            shell: bash
