name: 'helllicht/ftp-sync'
description: 'helllicht internal sync-action'

inputs:
    host:
        description: 'Host (e.g. "my-sftp-url.com")'
        required: true
    #port:
    #    description: 'Port [default: "22"]'
    #    required: false
    #    default: '22'
    #forceVendor:
    #    description: 'Always upload vendor (default: "false") ["false", all other strings are true!]'
    #    required: false
    #    default: 'false'
    username:
        description: 'Username'
        required: true
    password:
        description: 'Password'
        required: true
    localDir:
        description: 'Directory that should be uploaded (default: ".")'
        required: false
        default: '.'
    uploadPath:
        description: 'Path where the sync directory is (default: ".")'
        required: false
        default: '.'
    forceSSL:
        description: 'Just use SSL connection (default: "true") ["true"/"false"]'
        required: false
        default: 'true'
    parallel:
        description: 'Amount of parallel connections (default: "2")'
        required: false
        default: '2'

runs:
    using: "composite"
    steps:
        -   run: echo "Start helllicht/ftp-sync"
            shell: bash
        -   run: |
                chmod +x ${{ github.action_path }}/sync.sh
                bash ${{ github.action_path }}/sync.sh \
                    -s="${{ github.action_path }}" \
                    -h="${{ inputs.host }}" \
                    -u="${{ inputs.username }}" \
                    -p="${{ inputs.password }}" \
                    -l="${{ inputs.localDir }}" \
                    -r="${{ inputs.uploadPath }}" \
                    -S="${{ inputs.forceSSL }}" \
                    -P="${{ inputs.parallel }}" \
            shell: bash
